### ISSUE TITLE
Script doesn't work.

### ISSUE THREAD

**Issue by CHJ85** [benmoose39/ustvgo_to_m3u#1]
Hi there. None of the channels in the generated m3u playlist are working.
Also, the script was stuck in a loop trying to install dqdm. After I installed it myself using pip3 it generated the playlist just fine.
But like I said, the links do not work though.
Pasting em into the browser gives me a "forbidden" message.

**Comment by benmoose39** [comment]
It is clearly mentioned that the script generates a playlist which can only be played in the same network. Either you are taking it out of your local network or you are using a VPN.

**Comment by CHJ85** [comment]
Thanks. And you're right. It was the VPN thing.

**Comment by CHJ85** [comment]
Btw. Do you think you could make one of these for Sling TV please?

**Comment by benmoose39** [comment]
Looks like it's a paid service. If you make me an account I'll give it a try.

**Comment by CHJ85** [comment]
Yes, it is a paid service.
So I'm gonna have to send you my login info.
What's your email?

**Comment by benmoose39** [comment]
join my discord.

**Comment by CHJ85** [comment]
I don't use discord.
Here's the login. Just delete the message as soon as you got it.
user: giselle.suarez@mtlo.com
pass: Gisy1933

**Comment by CHJ85** [comment]
Have you looked into it yet?
Please keep me updated on the progress if you don't mind.
Thanks again.

**Comment by endochroma** [comment]
Don't post your account info anywhere online. People like me receive these comments in their email.

Change your password.

**Comment by CHJ85** [comment]
Right. But you and I are the only ones following this thread.
So have you looked into it yet?

**Comment by endochroma** [comment]
I'm not benmoose

**Comment by CHJ85** [comment]
@endochroma Yea I wasn't even looking at the name. 😀

**Comment by benmoose39** [comment]
benmoose39@gmail.com
But I don't check mails often. Come to discord if you can.
btw, like endochroma said, people get these comments in their email.

**Comment by CHJ85** [comment]
@benmoose39 Yea, I thought you weren't able to receive email notifications until you started posting in the thread.
It doesn't matter though. That Sling account is cancelled and will expire in a few weeks. Hopefully enough time.
