### ISSUE TITLE
Today I have problems with channels that use VPN

### ISSUE THREAD

**Issue by XtreamCP** [benmoose39/ustvgo_to_m3u#14]
I want to mention that I have been using your solution for a long time and you have done an excellent job, but as of today I have encountered a problem and all the channels that need VPN no longer work.

Do you have any idea how I can solve this without using a VPN?
Thanks

**Comment by ParrotDevelopers** [comment]
The fixed that bypass

**Comment by ParrotDevelopers** [comment]
Now u need to use NordVPN

**Comment by benmoose39** [comment]
looks like nordvpn is the only way.

**Comment by XtreamCP** [comment]
In fact, it works with TorGuard VPN, but it would have been much more useful if we could go over the VPN without everyone having to use it.

**Comment by XtreamCP** [comment]
It would not be possible to add a proxy, for example, to the ustvgo_m3ugrabber.py file so that it can be tricked.

**Comment by ParrotDevelopers** [comment]
you would need to host ur own proxy that would be connected with nordvpn

**Comment by ParrotDevelopers** [comment]
only nordvpn works btw

**Comment by ParrotDevelopers** [comment]
ustvgo is owned by nord
