### ISSUE TITLE
Possible Bug while installing script on remote server

### ISSUE THREAD

**Issue by inglesuniversal** [benmoose39/ustvgo_to_m3u#20]
script works fine locally but on remote server running python 3.9 the generated urls are not active or appear expired vs the local m3u version.

Any ideas how to fix this?

Regards

**Comment by Theitfixer85** [comment]
This isn't a bug - the public ip of the machine running the script must match the public ip address of the device playing it.

In other words - all devices must be on the same network with the same public ip address

You can get around this by restreaming the links eg by using xteve so you can access the restremed links via any network
