### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by JayG30** [benmoose39/ustvgo_to_m3u#22]
Should the ustv_go_channel_info.txt file be used for the EPG? I've tried to add it to xTeVe but it won't import.

**Comment by Theitfixer85** [comment]
I no longer make the epg public.

You can either find/create your own epg or join the discord and donate to sparklesunshine for the config files to use with WebGrabPlus. Details in the discord.

Also it wouldn't have been that file anyway. Epgs are xml files (or compressed xml usually in the gz format)
