### ISSUE TITLE
Missing 82. Nick Jr There seem to be 113 channels

### ISSUE THREAD

**Issue by SuperstationWTF** [benmoose39/ustvgo_to_m3u#26]
Thank you for your work. USTVGO now has 113 channels and it seems 82. Nick Jr is missing from the channels file. Just letting you know. Superstation WTF

**Comment by SuperstationWTF** [comment]
And now 29 Discovery Family for a total of 114! When will they end the madness! (got this from https://github.com/interlark/ustvgo-iptv/issues/57#issuecomment-1371279461)

**Comment by benmoose39** [comment]
added. Thanks for the heads up!
