### ISSUE TITLE
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)

### ISSUE THREAD

**Issue by bitsbb01** [benmoose39/ustvgo_to_m3u#5]
i keep getting this in the log.

python3 autoCRON.py
  shell: /usr/bin/bash -e {0}
TERM environment variable not set.
Collecting tqdm
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.62.3

Then it just keeps running saying:-
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)

**Comment by benmoose39** [comment]
Run it a second time and it should be fine.

**Comment by bitsbb01** [comment]
still saying "
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
Requirement already satisfied: tqdm in /home/runner/.local/lib/python3.8/site-packages (4.62.3)
"
its just going on and on... i'll try 
chmod +x autorun.sh
./autorun.sh

**Comment by bitsbb01** [comment]
nevermind, thats doing the same thing..

**Comment by benmoose39** [comment]
exit out of the script and run this:
`pip uninstall tqdm`
`python3 -m pip install tqdm`

**Comment by bitsbb01** [comment]
yep that worked.. thanks for the help there... 

So i'll show what i'm using to make it work, and it works perfectly now..

          
      - name: uninstall tqdm
        run: |
          pip uninstall tqdm
          python3 -m pip install tqdm
      - name: run script
        run: |
          chmod +x autorun.sh
          ./autorun.sh
      

Its creating the m3u perfectly... 
i gotta admit, all your scripts work so well, and they all work fast, and you do explain so well.. sometimes even with the simplest script there can be something goes wrong.. but your able to help so well..

Thank you...

**Comment by benmoose39** [comment]
:) 
Thank you!
